#!/bin/sh


# Capture a square video (1080x1080) starting from the top utmost left corner of the screen

NAME=$(date '+%Y-%m-%d_%H:%M:%S')

ffmpeg -f sndio -thread_queue_size 4096 -i snd/0.mon \
    -f sndio -thread_queue_size 4096 -i snd/1 \
    -filter_complex amix=inputs=2:duration=first:dropout_transition=2 \
    -y -f x11grab -thread_queue_size 4096 -s 1080x1080 -r 30 -i :0 \
    -c:v libx264rgb -crf 0 -b:v 10000k -preset ultrafast \
    -c:a flac -b:a 160k -ar 48000 \
    "$HOME/Videos/$NAME.mkv"
